// Read-only public SVG badge and representative supply receipts. Node20+.
import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const here=path.dirname(fileURLToPath(import.meta.url));
const out=path.resolve(process.argv[2]||path.join(here,'receipts'));
await fs.mkdir(out,{recursive:true});
const tokens=JSON.parse(await fs.readFile(path.join(here,'game-tokens.json'),'utf8'));
const beganAt=new Date().toISOString();
async function capture(name,url,payload){const startedAt=new Date().toISOString();let status=null,headers={},body='',error=null;try{const r=await fetch(url,{method:payload?'POST':'GET',headers:payload?{'Content-Type':'application/json'}:{Accept:'image/svg+xml'},...(payload?{body:JSON.stringify(payload)}:{}),signal:AbortSignal.timeout(20000)});status=r.status;headers=Object.fromEntries(r.headers.entries());body=await r.text();}catch(e){error=String(e);}const finishedAt=new Date().toISOString(),bodyFile=name+(payload?'.body.json':'.svg');await fs.writeFile(path.join(out,bodyFile),body);const receipt={name,url,method:payload?'POST':'GET',request:payload??null,status,headers,startedAt,finishedAt,error,bodyFile};await fs.writeFile(path.join(out,name+'.receipt.json'),JSON.stringify(receipt,null,2)+'\n');return{...receipt,body};}
const badges=[];
for(let i=0;i<tokens.length;i+=3){const batch=await Promise.all(tokens.slice(i,i+3).map(async t=>{const r=await capture('badge-'+String(t.tier).padStart(2,'0')+'-'+t.symbol.toLowerCase(),'https://scan.devfridge.cool/api/badge?mint='+encodeURIComponent(t.mint)+'&theme=dark&style=full');const text=[...r.body.matchAll(/<text\b[^>]*>(.*?)<\/text>/gs)].map(m=>m[1].replaceAll('&amp;','&').replaceAll('&lt;','<').replaceAll('&gt;','>').replaceAll('&quot;','"').replaceAll('&#39;',"'"));return{tier:t.tier,symbol:t.symbol,mint:t.mint,httpStatus:r.status,receipt:r.name+'.receipt.json',svg:r.bodyFile,text,status:text.some(s=>s.includes('temporarily unavailable'))?'unavailable':text.some(s=>s.includes('NOT FRIDGED'))?'no_open_vaults':'open_vault_badge',percentageText:text.join(' ').match(/\d+\.\d{2}%/)?.[0]??null,cacheControl:r.headers['cache-control']??null,age:r.headers.age??null,date:r.headers.date??null,startedAt:r.startedAt,finishedAt:r.finishedAt};}));badges.push(...batch);}
let supply=null;
for(const endpoint of ['https://solana-rpc.publicnode.com','https://api.mainnet-beta.solana.com']){const r=await capture('representative-supply-'+new URL(endpoint).hostname,endpoint,{jsonrpc:'2.0',id:1,method:'getTokenSupply',params:[tokens[0].mint,{commitment:'confirmed'}]});let j=null;try{j=JSON.parse(r.body);}catch{}if(r.status===200&&j?.result&&!j?.error){supply={status:'available',mint:tokens[0].mint,receipt:r.name+'.receipt.json',contextSlot:j.result.context?.slot??null,value:j.result.value,startedAt:r.startedAt,finishedAt:r.finishedAt};break;}}
const summary={beganAt,completedAt:new Date().toISOString(),readOnly:true,cookiesSent:false,refererSent:false,badges,representativeSupply:supply??{status:'unavailable'},formula:{numerator:'Sum raw amounts of every lock for the exact mint whose unlockAt is later than badge rendering time; all depositors included.',denominator:'Current getTokenSupply(mint).value.amount, same raw token units.',display:'(Number((BigInt(activeRawAmount)*10000n)/BigInt(supplyRaw))/100).toFixed(2)+"%"; integer division truncates to two decimal percentage places.',expiredUnclaimed:'An expired but unclaimed existing vault can still render FRIDGED without a percentage; it is not treated as currently timelocked in the percentage numerator.',unavailableSupply:'If supply is unavailable/nonpositive/invalid, omit percentage rather than infer a denominator.'},cache:{badgeRoute:'public, s-maxage=60, stale-while-revalidate=300',fridgeForMintProcessCacheMs:30000,supplyAndLocksSameSlot:false,note:'SVG supplies no embedded ledger slot or data capture timestamp. HTTP request times/Date/Age are delivery provenance, not synchronized chain snapshot time.'},meaning:'Token-wide percentage of supply in active DevFridge timelocks; neither game sessions nor player counts nor Android attribution.',gameIntegrationSource:'cold-storage/src/access-ui.ts:56 embeds one clickable full badge per character, linking to scan.devfridge.cool/t/<mint>.',currentAccessRule:'cold-storage/src/devfridge-locks.ts reads SDK activeLocks and validates depositor/mint/time; cold-storage/src/access.ts sums unique unexpired amounts per wallet/mint and unlocks at 500000 token units. SDK plan result/original minimum duration is not used as an access predicate here.',refererHandling:'Badge API can store up to 20 unique external referring domains per mint, once per domain; explicitly excludes hosts ending devfridge.cool. No per-request counter, wallet identity or gameplay event in this route.'};
await fs.writeFile(path.join(out,'summary.json'),JSON.stringify(summary,null,2)+'\n');
console.log(JSON.stringify({completedAt:summary.completedAt,badges:badges.map(b=>({symbol:b.symbol,status:b.httpStatus,percentage:b.percentageText,text:b.text})),representativeSupply:summary.representativeSupply},null,2));
